version: "3.8"
services:
    app:
        image: slrnt/dcigdl:latest
        container_name: dcigDL
        environment:
            - TOKEN=your_bot_token
            - REPO_URL=https://github.com/JonneSaloranta/dcigDL/
            - PUID=1000
            - PGID=1000
        restart: unless-stopped
        volumes:
            - /your/data/path:/app
